server:
  port: 8087

spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/founderlink_notifications
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  mail:
    host: ${SPRING_MAIL_HOST:${MAIL_HOST:smtp.gmail.com}}
    port: ${SPRING_MAIL_PORT:${MAIL_PORT:465}}
    username: ${SPRING_MAIL_USERNAME:${MAIL_USERNAME:abdulyahya9973@gmail.com}}
    password: ${SPRING_MAIL_PASSWORD:${MAIL_PASSWORD:xooecxywzeuahpng}}
    properties:
      mail:
        transport:
          protocol: smtps
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
          starttls:
            enable: false
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

resend:
  api-key: ${RESEND_API_KEY:}
  from-email: ${RESEND_FROM:FounderLink <onboarding@resend.dev>}

brevo:
  api-key: ${BREVO_API_KEY:}
  from-email: ${BREVO_FROM:abdulyahya9973@gmail.com}
  from-name: ${BREVO_NAME:FounderLink}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /notifications/v3/api-docs

rabbitmq:
  exchange: founderlink.exchange
  queue:
    investment-created: investment.created.queue
    investment-approved: investment.approved.queue
    team-invite-sent: team.invite.sent.queue
    startup-created: startup.created.queue
    startup-rejected: startup.rejected.queue
    payment-success: payment.success.queue
    payment-failed: payment.failed.queue
    user-registered: user.registered.queue

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
